<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
        <Nullable>disable</Nullable>
        <OutputType>Exe</OutputType>
        <LangVersion>preview</LangVersion>
        <ImplicitUsings>disable</ImplicitUsings>
        <TargetFramework>net462</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Playhead\Playhead.csproj" />
	</ItemGroup>

</Project>