<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net6.0;net7.0;net8.0;net9.0;net10.0;net11.0;net48;net481</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64;x86</Platforms>
    <Description>A modern, highly professional NowPlayingSessionManager (SMTC) wrapper library.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Authors>Taiizor</Authors>
    <Company>Taiizor</Company>
    <Copyright>Copyright © Taiizor 2026</Copyright>
    <RepositoryUrl>https://github.com/Taiizor/Playhead</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Taiizor/Playhead</PackageProjectUrl>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

</Project>
